name: Publish Gallery
on:
  push:
    branches:
      - main
    paths:
      - public/_gallery/**
  pull_request:
    branches:
      - main
    paths:
      - public/_gallery/**
permissions:
  id-token: write
  actions: write
  pages: write
  contents: write
jobs:
  deploy:
    name: Publish Gallery to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses:  actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build Gallery 🔧
        run: docker run -v "$(pwd):/work" ghcr.io/thumbsup/thumbsup /bin/sh -c "cd /work/ && thumbsup --config gallery-config.json"
      #- name: Deploy
      #  uses: s0/git-publish-subdir-action@develop
      #  env:
      #      REPO: self
      #      BRANCH: gh-pages
      #      FOLDER: build_output
      #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #      TARGET_DIR: gallery